import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { PhotoType } from "../@types/photos";
import Lightbox from "../components/lightbox";
import { getPhoto } from "../services/photos";

export const getServerSideProps: GetStaticProps = async (context) => {
  const { params } = context;
  const { photoId } = params || {};

  const id = typeof photoId === "string" ? photoId : undefined;

  if (!id) {
    return {
      notFound: true,
    };
  }

  const data = await getPhoto(id);

  return {
    props: {
      data: data,
    },
  };
};

const PhotoPage: NextPage<{ data: PhotoType }> = ({ data }) => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Lightbox
        setIsOpen={() => router.push("/")}
        isOpen={true}
        photos={[data]}
      />
    </>
  );
};

export default PhotoPage;
