import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/header";
import { Footer } from "../components/footer";
import Layout from "../components/layout";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Layout as="main">
        <div className="flex space-x-10">
          <figure className="flex-1">
            <Image
              src={""}
              alt=""
              className="outline-dotted w-full h-[400px]"
            />
          </figure>
          <section className="flex-1 flex flex-col">
            <h1 className="uppercase text-bold text-3xl mb-5">About</h1>
            <p className="mb-3 tracking-wide font-light text-xl">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Exercitationem sit adipisci officia culpa fugiat, explicabo optio
              dolorem doloremque possimus consequatur delectus amet suscipit qui
              nisi quia numquam, earum quam labore ipsam quas. At rem reiciendis
              sequi ipsa dolor facilis. Voluptates velit ab quas ipsa hic
              provident voluptatum. Nam, inventore tempore.
            </p>
            <p className="mb-3 tracking-wide font-light text-xl">
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Exercitationem sit adipisci officia culpa fugiat, explicabo optio
              dolorem doloremque possimus consequatur delectus amet suscipit qui
              nisi quia numquam.
            </p>
          </section>
        </div>
      </Layout>
      <Footer />
    </>
  );
};

export default Home;
