import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/header";
import { Footer } from "../components/footer";
import { Contact as ContactContrainer } from "../components/contact";
import Layout from "../components/layout";

const Contact: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Layout as="main">
        <ContactContrainer />
      </Layout>
      <Footer />
    </>
  );
};

export default Contact;
