import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/header";
import Newsletter from "../components/newsletter";
import Photos from "../components/photos";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Photos />
      <footer className="container mx-auto py-20 mt-[7.5rem] flex">
        <Newsletter />
      </footer>
    </>
  );
};

export default Home;
