import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../../components/header";
import { Footer } from "../../components/footer";
import Layout from "../../components/layout";
import { useRouter } from "next/router";
import { useQuery } from "react-query";
import { getPortfolio } from "../../services/portfolios";
import Photo from "../../components/photos-grid/photo";

const PortfolioIndexPage: NextPage = () => {
  const router = useRouter();
  const portfolioId = router.query.id as string;
  const { data, error, isLoading } = useQuery(["portfolio", portfolioId], () =>
    getPortfolio(portfolioId)
  );
  const { name, images = [] } = data || {};
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Layout>
        <>
          <h1>Portfolio {name}</h1>
          <span>Loading: {isLoading}</span>
          <span>Error: {JSON.stringify(error)}</span>
          <section className="flex flex-col gap-10">
            {images.map((image) => (
              <Photo
                key={image.id}
                alt={image.alt}
                src={image.src}
                height={image.height}
                width={image.width}
                blurDataURL={image.placeholder}
                style={{ width: "100%", maxHeight: "1200px", objectFit:"cover" }}
              />
            ))}
          </section>
        </>
      </Layout>
      <Footer />
    </>
  );
};

export default PortfolioIndexPage;
