import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../../components/header";
import { Footer } from "../../components/footer";
import Layout from "../../components/layout";
import { useRouter } from "next/router";
import { useQuery } from "react-query";
import { getPortfolio } from "../../services/portfolios";

const PortfolioIndexPage: NextPage = () => {
  const router = useRouter();
  const portfolioId = router.query.id as string;
  const { data, error, isLoading } = useQuery(["portfolio", portfolioId], () =>
    getPortfolio(portfolioId)
  );
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Layout>
        <>
          <h1>Portfolio {portfolioId}</h1>
          Loading: {isLoading}
          Error: {JSON.stringify(error)}
          {JSON.stringify(data)}
        </>
      </Layout>
      <Footer />
    </>
  );
};

export default PortfolioIndexPage;
