import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { getPortfolio } from "../../../services/portfolios";
import { Portfolio } from "../../../@types/portfolios";
import { Lightbox } from "../../../components/lightbox";

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const portfolioId = ctx.params?.id as string;

  const data = await getPortfolio(portfolioId);
  return {
    props: { portfolio: data },
  };
};

const PortfolioImageIndexPage: NextPage<{ portfolio: Portfolio }> = ({
  portfolio,
}) => {
  const router = useRouter();
  const { imageId, id: portfolioId } = router.query;
  const startIndex = portfolio.images.findIndex(
    (image) => image.id === imageId
  );
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Lightbox
        initialIndex={startIndex}
        photos={portfolio.images}
        onClose={() => router.push(`/portfolio/${portfolioId}`)}
      />
    </>
  );
};

export default PortfolioImageIndexPage;
